name: chat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  modal_progress_hud_nsn: ^0.5.1
  cloud_firestore: ^6.0.3
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints
  # to encourage good coding practices.
  flutter_lints: ^5.0.0

flutter:
  # Ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section like this:
  assets:
    - assets/images/scholar.png

  # To add custom fonts to your application, add a fonts section here.
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
